ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS region_id VARCHAR(30);
ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE news_articles ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION;
CREATE INDEX IF NOT EXISTS idx_news_region ON news_articles(region_id);
